import { BlogPost } from './types';

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: 'The Future of AI in Enterprise',
    excerpt:
      'Exploring how artificial intelligence is transforming business operations and revolutionizing decision-making processes across industries...',
    content: 'Full content here...',
    author: 'Dr. Sarah Chen',
    date: 'Mar 15, 2024',
    image: 'https://source.unsplash.com/800x600/?artificial-intelligence',
    category: 'AI Trends',
    readTime: '8 min',
    tags: ['AI', 'Enterprise', 'Digital Transformation'],
  },
  {
    id: 2,
    title: 'Machine Learning Best Practices',
    excerpt:
      'Key considerations for implementing ML models in production environments, including testing, monitoring, and maintenance strategies...',
    content: 'Full content here...',
    author: 'James Wilson',
    date: 'Mar 12, 2024',
    image: 'https://source.unsplash.com/800x600/?machine-learning',
    category: 'Technical',
    readTime: '12 min',
    tags: ['Machine Learning', 'DevOps', 'Best Practices'],
  },
  {
    id: 3,
    title: 'Data Privacy in AI Systems',
    excerpt:
      'Understanding the importance of data protection in AI development and implementing robust security measures...',
    content: 'Full content here...',
    author: 'Emma Thompson',
    date: 'Mar 10, 2024',
    image: 'https://source.unsplash.com/800x600/?data-security',
    category: 'Security',
    readTime: '10 min',
    tags: ['Privacy', 'Security', 'GDPR'],
  },
  {
    id: 4,
    title: 'Natural Language Processing Breakthroughs',
    excerpt:
      'Recent advances in NLP are pushing the boundaries of human-computer interaction and language understanding...',
    content: 'Full content here...',
    author: 'Dr. Michael Chang',
    date: 'Mar 8, 2024',
    image: 'https://source.unsplash.com/800x600/?natural-language-processing',
    category: 'Research',
    readTime: '15 min',
    tags: ['NLP', 'Research', 'Innovation'],
  },
  {
    id: 5,
    title: 'Ethical AI Development',
    excerpt:
      'Exploring the ethical considerations and responsibilities in artificial intelligence development and deployment...',
    content: 'Full content here...',
    author: 'Prof. Lisa Martinez',
    date: 'Mar 5, 2024',
    image: 'https://source.unsplash.com/800x600/?ethics',
    category: 'Ethics',
    readTime: '11 min',
    tags: ['Ethics', 'AI', 'Responsibility'],
  },
  {
    id: 6,
    title: 'Edge Computing and AI',
    excerpt:
      'How edge computing is enabling real-time AI applications and transforming IoT implementations...',
    content: 'Full content here...',
    author: 'Robert Kumar',
    date: 'Mar 3, 2024',
    image: 'https://source.unsplash.com/800x600/?edge-computing',
    category: 'Technical',
    readTime: '9 min',
    tags: ['Edge Computing', 'IoT', 'Infrastructure'],
  },
  {
    id: 7,
    title: 'AI in Healthcare: 2024 Outlook',
    excerpt:
      'Examining the latest applications of AI in healthcare and predictions for future developments...',
    content: 'Full content here...',
    author: 'Dr. Jennifer White',
    date: 'Feb 28, 2024',
    image: 'https://source.unsplash.com/800x600/?healthcare-technology',
    category: 'Healthcare',
    readTime: '13 min',
    tags: ['Healthcare', 'AI Applications', 'Future Tech'],
  },
  {
    id: 8,
    title: 'Deep Learning Architecture Patterns',
    excerpt:
      'A comprehensive guide to effective deep learning architecture patterns and their implementations...',
    content: 'Full content here...',
    author: 'Alex Rodriguez',
    date: 'Feb 25, 2024',
    image: 'https://source.unsplash.com/800x600/?deep-learning',
    category: 'Technical',
    readTime: '14 min',
    tags: ['Deep Learning', 'Architecture', 'Neural Networks'],
  },
  {
    id: 9,
    title: 'AI-Powered Cybersecurity',
    excerpt:
      'How artificial intelligence is revolutionizing threat detection and response in cybersecurity...',
    content: 'Full content here...',
    author: 'David Anderson',
    date: 'Feb 22, 2024',
    image: 'https://source.unsplash.com/800x600/?cybersecurity',
    category: 'Security',
    readTime: '10 min',
    tags: ['Cybersecurity', 'AI', 'Threat Detection'],
  },
  {
    id: 10,
    title: 'Quantum Computing and AI',
    excerpt:
      'Exploring the intersection of quantum computing and artificial intelligence, and its potential impact...',
    content: 'Full content here...',
    author: 'Dr. Richard Lee',
    date: 'Feb 20, 2024',
    image: 'https://source.unsplash.com/800x600/?quantum-computing',
    category: 'Research',
    readTime: '16 min',
    tags: ['Quantum Computing', 'AI', 'Future Tech'],
  },
];
